Feat/perper collections
obecto/perper pull request #92
Opened 2022-03-27 18:05 UTC by iovigi

Adding perper collection

2022-03-28 12:26 UTC, bojidar-bg requested changes
Overall: I like the interface and the direction the whole thing is taking, but I feel like the performance should be given some more attention. As mentioned, the fact that you store `${index}-${key}` as keys means that despite ignite cache's get-by-key being ~`O(1)`, PerperCollection's  get-by-key is `O(n)`.
(And finally: I can't quite seem to spot a `GetByIndex` operation...)
Also, assume that the same PerperCollection can be accessed by two different processes simultaneously, any of which can crash. Even if it doesn't work as good as when used by one process, it should degrade as gracefully as possible. So, it's better that we get slower writes as the two processes are competing to increment the next index, instead of one overwriting an item due to both of them adding a new item at the same time.

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/PerperCollection.cs
> +                .FirstOrDefaultAsync(predicate)
This is `O(n)` and transfers the whole contents of the cache over the connection between Ignite and the agent. We need a faster way to do it, as it is used in every operation, including in `get`, an operation supposed to be `O(1)`.

I can see two ways to do this:
1. Drop the functionality that has all elements accessible both by numeric index and string key. This is similar to what Javascript objects and Lua tables implement; and I can't think of a language allowing an item added with a string to be accessed by numeric index.
(Then, instead of storing `"1-" => A, "2-x" => B`, store `"1" => A, "-x" => B`)
2. Introduce a level of indirection when storing an item by both index and key; for example, store the index at the string key and then store the real object at the index.
(So, instead of storing `(1,x) => A`, store `x => 1` and `1 => A`)

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/PerperCollection.cs
> +            await configCache.PutAsync("end_index", lastIndex).ConfigureAwait(false);
This can race (consider what happens when two processes call `GetNextIndex` at the same time).
Consider using `Perper.Protocol.IgniteCacheExtensions.OptimisticUpdateAsync`, as it already has most of the logic in place.
Same for `{In,De}crementCount`

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/PerperCollection.cs
> +            configCache.Put("count", 0);
We don't need count; we can compute count (a rare operation) by just doing `end - start`, and get faster writes (a common operation) due to needing to update less keys.

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/PerperCollection.cs
> +            configCache.Put("count", 0);
1. Would suggest using default values for those three instead of setting initial values.
2. With this in the `PerperCollection` constructor, you can't actually restart the agent's container due as the code would run again and mess the indexes up.

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/PerperCollection.cs
> +            AsyncLocals.FabricService.GetCollectionCache<int>(AsyncLocals.Instance, $"{name}-meta");
In Ignite 2.x, you can make use of the fact that caches are completely untyped; that is, there is no problem in getting a `ICacheClient<string, int>` and a `ICacheClient<string, T>` for the same cache.
(In fact, you can even have a `ICacheClient<int, T>` for that same cache)

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Protocol/FabricService.Collection.cs
> +        }
(minor) Dead code. (Feel free to just remove the `{TryGet,Set,Remove}CollectionValue` functions and keep everything in `PerperCollection` for now, as the DI changes would be refactoring FabricService anyway.)

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/PerperCollection.cs
> +            await configCache.PutAsync("start_index", startIndex + 1).ConfigureAwait(false);
Can race. (TOCTOU; there is no guarantee that no one changed `start_index` before you get to increment it)

2022-03-28 12:26 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/PerperCollection.cs
> +            await AddAsync(value)
This can race. (Both threads might return 1 if they both go through `ContainsKeyAsync` before either gets to `AddAsync`)

2022-03-29 08:37 UTC, bojidar-bg reviewed
Looks good overall, left a few comments. (:
I wonder whether it would make sense to add `SetAsync`, `SetIfNotExistingAsync`, and `SetIfNotChangedAsync` to `IAsyncDictionary`, and perhaps consider `SetAsync` and `SetIfNotChangedAsync` for `PerperList`/`IAsyncList`. Tho, we can do that later down the road, so it's not blocking.

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/IAsyncList.cs
> +        public string Name { get; }
Either none or both of `IAsync{List,Dictionary}` should have a name property.

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +            .ConfigureAwait(false);
Wouldn't it be simpler to directly get the value at `item.Key` and check if it equals `item.Value`?

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +            .CountAsync()
`.ToAsyncEnumerable()` would actually stream everything that matches the queriable from the Ignite cluster. It would be faster to do `Task.Run(() => DataCache.AsCacheQueryable().Count())`.

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +        public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator() => GetEnumerator();
I might be wrong, but isn't this a recursive call? (Same for PerperList)

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +            .Select(x => x.Key)
```suggestion
            .Select(x => x.Key)
            .ToAsyncEnumerable()
```

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +            .Select(x => x.Value)
```suggestion
            .Select(x => x.Value)
            .ToAsyncEnumerable()
```

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +        public async Task<bool> SetIfNotChanged(TKey key, TValue oldValue, TValue newValue)
```suggestion
        public async Task<bool> SetIfNotChangedAsync(TKey key, TValue oldValue, TValue newValue)
```

2022-03-29 08:37 UTC, bojidar-bg commented on agent/dotnet/src/Perper/Extensions/Collections/PerperList.cs
> +            var index = dataCache
Reuse `IndexOf(item)` (same for `RemoveAsync`)

2022-03-29 09:55 UTC, iovigi commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +        public IEnumerator<KeyValuePair<TKey, TValue>> GetEnumerator() => GetEnumerator();
It isn't recursive, there is a second method GetEnumerator. This is a pattern of implementation by Microsoft. Probably someday they will remove the second method, but I think they keep it for backward compatibility.

2022-03-29 10:33 UTC, iovigi commented on agent/dotnet/src/Perper/Extensions/Collections/PerperDictionary.cs
> +            .ConfigureAwait(false);
I don't get it

2022-04-05 06:13 UTC, bojidar-bg approved these changes
Look good to merge.

2022-04-05 06:18 UTC, merged